# Project
version=7.0.0
group=absolemjackdaw
java_version=21
releasetype=release
changelog=update to 1.21.11
# Common
minecraft_version=1.21.11
parchment_minecraft=1.21.10
parchment_version=2025.10.12
neo_form_version=1.21.11-20251209.172050
# NeoForge
neoforge_version=21.11.17-beta
neoforge_loader_version_range=[4,)
# Fabric
fabric_version=0.140.2+1.21.11
fabric_loader_version=0.18.4
# Mod options
mod_name=LeftHanging
mod_author=AbsolemJackdaw
mod_id=hangman
license=MIT
credits=My dark twisted sense of humor. [1.19.3, 1.20.1 port: Duzos][1.21 aid: Daniel Rugusa] [1.21.11: fabric mixin help from LlamaLad7]
minecraft_version_range=[1.21.11, 1.22)
description=Left Hanging is a decorative mod themed for halloween.\nYou can hang entities for decoration, or yourself if you wanted to.\nThe noose can also be used as a trap to catch and kill mobs.
common_runs_enabled=false
# publishing
modrinth_project=usn7e1Yk
cf_project=532595
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false