modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU3"
issueTrackerURL="" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="hangman" #mandatory
version="${file.jarVersion}" #mandatory
displayName="HangMan" #mandatory
logoFile="examplemod.png" #optional
credits="my dark twisted sense of humor" #optional
authors="AbsolemJackdaw, Subaraki" #optional
description='''
Left Hanging is a decorative mod themed for halloween.
You can hang entities for decoration, or yourself if you wanted to.
The noose can also be used as a trap to catch and kill mobs.
'''
[[dependencies.hangman]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.hangman]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
